name: Build and Push Lambda Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::914926217697:role/github-ecr-lambda
          aws-region: ap-south-1
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        run: |
          docker build -t quotation-generator .
          docker tag quotation-generator:latest \
          914926217697.dkr.ecr.ap-south-1.amazonaws.com/quotation-generator:latest
          docker push \
          914926217697.dkr.ecr.ap-south-1.amazonaws.com/quotation-generator:latest
